package me.rafaelldi.aspire.util

const val DEBUG_SESSION_TOKEN = "DEBUG_SESSION_TOKEN"
const val DEBUG_SESSION_PORT = "DEBUG_SESSION_PORT"
const val ASPNETCORE_URLS = "ASPNETCORE_URLS"
const val DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS = "DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS"
const val DOTNET_DASHBOARD_FRONTEND_BROWSERTOKEN = "DOTNET_DASHBOARD_FRONTEND_BROWSERTOKEN"
const val DOTNET_DASHBOARD_RESOURCESERVICE_APIKEY = "DOTNET_DASHBOARD_RESOURCESERVICE_APIKEY"
const val ASPIRE_ALLOW_UNSECURED_TRANSPORT = "ASPIRE_ALLOW_UNSECURED_TRANSPORT"
const val DOTNET_RESOURCE_SERVICE_ENDPOINT_URL = "DOTNET_RESOURCE_SERVICE_ENDPOINT_URL"
const val DOTNET_ASPIRE_CONTAINER_RUNTIME = "DOTNET_ASPIRE_CONTAINER_RUNTIME"