package me.rafaelldi.aspire.util

const val DEBUG_SESSION_TOKEN = "DEBUG_SESSION_TOKEN"
const val DEBUG_SESSION_PORT = "DEBUG_SESSION_PORT"
const val ASPNETCORE_URLS = "ASPNETCORE_URLS"
const val DOTNET_DASHBOARD_FRONTEND_AUTHMODE = "DOTNET_DASHBOARD_FRONTEND_AUTHMODE"
const val DOTNET_DASHBOARD_FRONTEND_BROWSERTOKEN = "DOTNET_DASHBOARD_FRONTEND_BROWSERTOKEN"
const val BROWSER_TOKEN = "BrowserToken"
const val ASPIRE_ALLOW_UNSECURED_TRANSPORT = "ASPIRE_ALLOW_UNSECURED_TRANSPORT"
const val DOTNET_RESOURCE_SERVICE_ENDPOINT_URL = "DOTNET_RESOURCE_SERVICE_ENDPOINT_URL"
const val DOTNET_DASHBOARD_OTLP_ENDPOINT_URL = "DOTNET_DASHBOARD_OTLP_ENDPOINT_URL"