// <auto-generated/>
namespace JetBrains.Rider.Aspire.Plugin.Resources
{
  using System;
  using JetBrains.Application.I18n;
  using JetBrains.DataFlow;
  using JetBrains.Diagnostics;
  using JetBrains.Lifetimes;
  using JetBrains.Util;
  using JetBrains.Util.Logging;
  using JetBrains.Application.I18n.Plurals;
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal static class Strings
  {
    private static readonly ILogger ourLog = Logger.GetLogger("JetBrains.Rider.Aspire.Plugin.Resources.Strings");

    static Strings()
    {
      CultureContextComponent.Instance.Change.Advise(Lifetime.Eternal, args =>
      {
          var instance = args.HasNew ? args.New : null;
          if (instance != null)
          {
            ourResourceManager = new Lazy<JetResourceManager>(
              () =>
              {
                return instance
                  .CreateResourceManager("JetBrains.Rider.Aspire.Plugin.Resources.Strings", typeof(Strings).Assembly);
              });
          }
          else
          {
            ourResourceManager = null;
          };
      });
    }
    
    private static Lazy<JetResourceManager> ourResourceManager = null;
    
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static JetResourceManager ResourceManager
    {
      get
      {
        var resourceManager = ourResourceManager;
        if (resourceManager == null)
        {
          return ErrorJetResourceManager.Instance;
        }
        return resourceManager.Value;
      }
    }

    public static string Choice(string format, params object[] args)
    {
        var formatter = ResourceManager.ChoiceFormatter;
        if (formatter == null) return "???";
        return string.Format(formatter, format, args);
    }

    public static string RestartWithoutDebugger => ResourceManager.GetString("RestartWithoutDebugger");
    public static string RestartWithDebugger => ResourceManager.GetString("RestartWithDebugger");
    public static string Start => ResourceManager.GetString("Start");
    public static string Stop => ResourceManager.GetString("Stop");
    public static string Restart => ResourceManager.GetString("Restart");
    public static string Rebuild => ResourceManager.GetString("Rebuild");
    public static string Building => ResourceManager.GetString("Building");
    public static string Starting => ResourceManager.GetString("Starting");
    public static string Running => ResourceManager.GetString("Running");
    public static string FailedToStart => ResourceManager.GetString("FailedToStart");
    public static string RuntimeUnhealthy => ResourceManager.GetString("RuntimeUnhealthy");
    public static string Stopping => ResourceManager.GetString("Stopping");
    public static string Exited => ResourceManager.GetString("Exited");
    public static string Finished => ResourceManager.GetString("Finished");
    public static string Waiting => ResourceManager.GetString("Waiting");
    public static string NotStarted => ResourceManager.GetString("NotStarted");
    public static string Hidden => ResourceManager.GetString("Hidden");
    public static string Unknown => ResourceManager.GetString("Unknown");
    public static string ExitCode => ResourceManager.GetString("ExitCode");
    public static string AspireResource => ResourceManager.GetString("AspireResource");
    public static string Healthy => ResourceManager.GetString("Healthy");
    public static string Unhealthy => ResourceManager.GetString("Unhealthy");
    public static string Degraded => ResourceManager.GetString("Degraded");
  }
}