<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>3f0c1d84-6b2a-42e7-9d5f-8ac3e17b40d9</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\WpfAspireApp.WpfApp\WpfAspireApp.WpfApp.csproj" />
    </ItemGroup>

</Project>
