package com.jetbrains.aspire.rider.run.file

import com.intellij.execution.RunManager
import com.intellij.execution.configurations.ConfigurationTypeUtil
import com.intellij.openapi.application.EDT
import com.intellij.openapi.components.Service
import com.intellij.openapi.components.service
import com.intellij.openapi.diagnostic.logger
import com.intellij.openapi.project.Project
import com.jetbrains.aspire.rider.launchProfiles.getFileBasedLaunchProfiles
import com.jetbrains.aspire.rider.run.AspireConfigurationType
import com.jetbrains.rider.projectView.solutionDirectory
import com.jetbrains.rider.run.AutoGeneratedRunConfigurationManager
import com.jetbrains.rider.run.configurations.RunConfigurationHelper.hasConfigurationForNameAndTypeId
import com.jetbrains.rider.run.configurations.launchSettings.LaunchSettingsJsonService
import com.jetbrains.rider.util.idea.getService
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.Json
import java.nio.file.Path
import kotlin.io.path.exists
import kotlin.io.path.extension
import kotlin.io.path.nameWithoutExtension
import kotlin.io.path.readText

/**
 * Generates default [AspireFileConfiguration]s for a file-based app host described by an
 * [ASPIRE_CONFIG_JSON_NAME] file, mirroring [AspireConfigurationType.tryCreateDefault].
 *
 * A configuration is generated only when `aspire.config.json` points (via `appHost.path`) to a
 * single-file app host (a `.cs` file rather than a `.csproj`).
 */
@Service(Service.Level.PROJECT)
internal class AspireFileConfigurationGenerator(private val project: Project) {
    companion object {
        fun getInstance(project: Project) = project.service<AspireFileConfigurationGenerator>()

        private val LOG = logger<AspireFileConfigurationGenerator>()

        private const val PROFILE_PARAMETER = "aspireProfileName"

        private val json by lazy {
            Json { ignoreUnknownKeys = true }
        }
    }

    suspend fun generateDefaultConfigurations() {
        val configPath = project.solutionDirectory.toPath().resolve(ASPIRE_CONFIG_JSON_NAME)
        if (!configPath.exists()) return

        val config = runCatching {
            withContext(Dispatchers.IO) {
                json.decodeFromString<AspireConfigJson>(configPath.readText())
            }
        }.getOrElse {
                LOG.warn("Unable to parse $configPath", it)
                return
            }

        val appHostPath = config.appHost?.path ?: return
        //If the appHostPath is an absolute path then resolve returns appHostPath.
        val resolvedAppHostPath = configPath.parent?.resolve(appHostPath)?.normalize() ?: return

        // Only file-based app hosts (a single `.cs` file) are handled here; project-based app hosts
        // (`.csproj`) are covered by AspireConfigurationType.tryCreateDefault.
        if (!resolvedAppHostPath.extension.equals("cs", true)) return
        if (!resolvedAppHostPath.exists()) return

        val profiles = LaunchSettingsJsonService.getInstance(project).getFileBasedLaunchProfiles(configPath)
        if (profiles.isEmpty()) return

        val runManager = RunManager.getInstanceAsync(project)
        val autoGeneratedRunConfigurationManager = project.getService<AutoGeneratedRunConfigurationManager>()
        val factory = ConfigurationTypeUtil
            .findConfigurationType(AspireConfigurationType::class.java)
            .fileFactory
        withContext(Dispatchers.EDT) {
            for ((name) in profiles) {
                generateConfigurationForProfile(
                    resolvedAppHostPath,
                    name,
                    runManager,
                    autoGeneratedRunConfigurationManager,
                    factory
                )
            }
        }
    }

    private fun generateConfigurationForProfile(
        appHostPath: Path,
        profileName: String,
        runManager: RunManager,
        autoGeneratedRunConfigurationManager: AutoGeneratedRunConfigurationManager,
        factory: AspireFileConfigurationFactory
    ) {
        val appHostFilePath = appHostPath.toString()

        if (hasRunConfigurationEverBeenGenerated(autoGeneratedRunConfigurationManager, appHostFilePath, profileName)) {
            return
        }

        val appHostName = appHostPath.nameWithoutExtension
        val configurationName =
            if (appHostName == profileName) profileName
            else "$appHostName: $profileName"

        if (runManager.hasConfigurationForNameAndTypeId(configurationName, AspireConfigurationType.ID) ||
            runManager.hasConfigurationForNameAndTypeId(appHostName, AspireConfigurationType.ID)
        ) return

        val settings = runManager.createConfiguration(configurationName, factory).apply {
            isActivateToolWindowBeforeRun = false
            isFocusToolWindowBeforeRun = false
        }
        (settings.configuration as? AspireFileConfiguration)?.parameters?.apply {
            this.filePath = appHostFilePath
            this.profileName = profileName
        }

        runManager.addConfiguration(settings)
        markProjectAsAutoGenerated(autoGeneratedRunConfigurationManager, appHostFilePath, profileName)

        LOG.trace("Generated default file-based Aspire configuration \"$configurationName\"")
    }

    private fun hasRunConfigurationEverBeenGenerated(
        autoGeneratedRunConfigurationManager: AutoGeneratedRunConfigurationManager,
        appHostFilePath: String,
        profileName: String
    ) = autoGeneratedRunConfigurationManager.hasRunConfigurationEverBeenGenerated(
        appHostFilePath,
        mapOf(PROFILE_PARAMETER to profileName)
    )

    private fun markProjectAsAutoGenerated(
        autoGeneratedRunConfigurationManager: AutoGeneratedRunConfigurationManager,
        appHostFilePath: String,
        profileName: String
    ) {
        autoGeneratedRunConfigurationManager.markProjectAsAutoGenerated(
            appHostFilePath,
            mapOf(PROFILE_PARAMETER to profileName)
        )
    }
}
